# -*- coding: utf-8 -*-
"""#3: Linear Regression Multiple Variables

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zsbRP5vp14LcL8dyDvjCIG57lE6php_l
"""

import pandas as pd
import numpy as np
from sklearn import linear_model

df = pd.read_csv('homeprices2.csv')
df

# prompt: Using dataframe df: delete the 6th row

df.drop(df.index[-1], inplace=True)
df

# calculate median, store in a variable, replace all NaN with the variable
import math
bedMedian = math.floor(df['bedrooms'].median())
bedMedian

df.bedrooms.fillna(bedMedian)

df.bedrooms = df.bedrooms.fillna(bedMedian)
df
# to make it look better

reg = linear_model.LinearRegression()
reg.fit(df[['area', 'bedrooms', 'age']], df[['price']])
# first 3 variables are independent variables and the last one is the target variable, or dependent

reg.coef_
# first is m1, then m2, and lastly m3
# formula --> price = m1*area + m2*bedrooms + m3*age + b

reg.intercept_
# variable b in the formula

reg.predict([[3000, 3, 40]])

reg.predict([[3000, 3, 40]])

reg.predict([[2500,4,5]])